package Model;
// Generated Dec 16, 2020 9:59:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name="tag"
    ,catalog="timelive"
    , uniqueConstraints = @UniqueConstraint(columnNames="tag") 
)
public class Tag  implements java.io.Serializable {


     private Integer tagid;
     private Users users;
     private String tag;
     private String color;
     private Set<Task> tasks = new HashSet<Task>(0);
     private Set<Todo> todos = new HashSet<Todo>(0);

    public Tag() {
    }

    public Tag(Integer tagid, String tag, String color) {
        this.tagid = tagid;
        this.tag = tag;
        this.color = color;
    }

    public Tag(Integer tagid, Users users, String tag, String color) {
        this.tagid = tagid;
        this.users = users;
        this.tag = tag;
        this.color = color;
    }
    
    public Tag(Users users, String tag, String color) {
        this.users = users;
        this.tag = tag;
        this.color = color;
    }
    public Tag(Users users, String tag, String color, Set<Task> tasks, Set<Todo> todos) {
       this.users = users;
       this.tag = tag;
       this.color = color;
       this.tasks = tasks;
       this.todos = todos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tagid", unique=true, nullable=false)
    public Integer getTagid() {
        return this.tagid;
    }
    
    public void setTagid(Integer tagid) {
        this.tagid = tagid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userid", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="tag", unique=true, nullable=false, length=30)
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }

    
    @Column(name="color", nullable=false, length=7)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tag")
    public Set<Task> getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set<Task> tasks) {
        this.tasks = tasks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tag")
    public Set<Todo> getTodos() {
        return this.todos;
    }
    
    public void setTodos(Set<Todo> todos) {
        this.todos = todos;
    }




}


