package Model;
// Generated Jan 1, 2021 11:27:16 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name="task"
    ,catalog="timelive"
)
public class Task  implements java.io.Serializable {


     private Integer taskid;
     private Tag tag;
     private Users users;
     private Date deadline;
     private Boolean done;
     private Date doneat;
     private String taskname;

    public Task() {
    }

	
    public Task(Users users) {
        this.users = users;
    }
    public Task(Tag tag, Users users, Date deadline, Boolean done, Date doneat, String taskname) {
       this.tag = tag;
       this.users = users;
       this.deadline = deadline;
       this.done = done;
       this.doneat = doneat;
       this.taskname = taskname;
    }

    public Task(Tag tag, Users users, Date deadline, Boolean done, String taskname) {
        this.tag = tag;
        this.users = users;
        this.deadline = deadline;
        this.done = done;
        this.taskname = taskname;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="taskid", unique=true, nullable=false)
    public Integer getTaskid() {
        return this.taskid;
    }
    
    public void setTaskid(Integer taskid) {
        this.taskid = taskid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tagid")
    public Tag getTag() {
        return this.tag;
    }
    
    public void setTag(Tag tag) {
        this.tag = tag;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userid", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deadline", length=19)
    public Date getDeadline() {
        return this.deadline;
    }
    
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    
    @Column(name="done")
    public Boolean getDone() {
        return this.done;
    }
    
    public void setDone(Boolean done) {
        this.done = done;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="doneat", length=19)
    public Date getDoneat() {
        return this.doneat;
    }
    
    public void setDoneat(Date doneat) {
        this.doneat = doneat;
    }

    
    @Column(name="taskname", length=45)
    public String getTaskname() {
        return this.taskname;
    }
    
    public void setTaskname(String taskname) {
        this.taskname = taskname;
    }
}


