package Model;
// Generated Dec 16, 2020 9:59:07 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Weekly generated by hbm2java
 */
@Entity
@Table(name="weekly"
    ,catalog="timelive"
)
public class Weekly  implements java.io.Serializable {


     private WeeklyId id;
     private Routines routines;
     private Users users;

    public Weekly() {
    }

	
    public Weekly(WeeklyId id, Users users) {
        this.id = id;
        this.users = users;
    }
    public Weekly(WeeklyId id, Routines routines, Users users) {
       this.id = id;
       this.routines = routines;
       this.users = users;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="wid", column=@Column(name="wid", nullable=false) ), 
        @AttributeOverride(name="userid", column=@Column(name="userid", nullable=false) ) } )
    public WeeklyId getId() {
        return this.id;
    }
    
    public void setId(WeeklyId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="routineid")
    public Routines getRoutines() {
        return this.routines;
    }
    
    public void setRoutines(Routines routines) {
        this.routines = routines;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userid", nullable=false, insertable=false, updatable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


