package Model;
// Generated Dec 16, 2020 9:59:07 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WeeklyId generated by hbm2java
 */
@Embeddable
public class WeeklyId  implements java.io.Serializable {


     private int wid;
     private int userid;

    public WeeklyId() {
    }

    public WeeklyId(int wid, int userid) {
       this.wid = wid;
       this.userid = userid;
    }
   


    @Column(name="wid", nullable=false)
    public int getWid() {
        return this.wid;
    }
    
    public void setWid(int wid) {
        this.wid = wid;
    }


    @Column(name="userid", nullable=false)
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WeeklyId) ) return false;
		 WeeklyId castOther = ( WeeklyId ) other; 
         
		 return (this.getWid()==castOther.getWid())
 && (this.getUserid()==castOther.getUserid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getWid();
         result = 37 * result + this.getUserid();
         return result;
   }   


}


